name: Check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: check-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    name: Nix configuration
    runs-on: macos-15
    timeout-minutes: 60

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@61cbfe2efc2d4e7a8a6d56967c3c1058e846c858 # v3.21.9

      - name: Check formatting
        run: nix fmt -- --ci

      - name: Check flake
        run: nix flake check

      - name: Build macOS configuration
        run: nix build '.#darwinConfigurations.KobayashinoMacBook-Pro.system' --no-link
